apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAgICJhdXRoIjogIlptOTRlUzFuWVd3NloyaHdYMW93VEU0Mk1HaFpTSFpSV1ZWNFFUSlZlVFZzVldac1RrdERiRTFoY3pGRlFucFdWUT09IgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
